name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag (Git commit SHA)"
        required: true
        type: string

env:
  AWS_REGION: ap-south-1
  TF_DIR: terraform

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init \
            -reconfigure \
            -backend-config="environments/dev/backend.hcl"

      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform apply \
            -auto-approve \
            -var-file="environments/dev/dev.tfvars" \
            -var="image_tag=${{ github.event.inputs.image_tag }}" \
            -var="database_password=${DB_PASSWORD}" 